In [1]:
print("Hello")

Hello


In [30]:
import numpy as np
from sympy import symbols, Matrix
from sympy.utilities.lambdify import lambdify
from scipy.linalg import eigh

def solve_hamiltonian_fixed_j1_j4(hamiltonian, params, constant_values, j2_range, j3_range, filename="hamiltonian_results_j1_1_j2_j3.csv"):
    """
    Solves a symbolic Hamiltonian with j1 and j4 constant, looping over j2 and j3 independently.
    Saves eigenvalues as separate columns and only the first eigenvector.
    
    Parameters:
    - hamiltonian: SymPy matrix representing the Hamiltonian.
    - params: List of sympy symbols used as variables.
    - constant_values: Dictionary with fixed values for parameters.
    - j2_range: Tuple (start, stop, step) for j2.
    - j3_range: Tuple (start, stop, step) for j3.
    - filename: Output file name for results.
    """
    # Substitute constant values
    hamiltonian_substituted = hamiltonian.subs(constant_values)
    varying_params = [p for p in params if p not in constant_values]
    
    # Convert symbolic matrix to numerical function
    h_func = lambdify(varying_params, hamiltonian_substituted, modules="numpy")

    # Prepare file for writing results
    with open(filename, 'w') as file:
        # Header setup
        num_eigenvalues = hamiltonian.shape[0]
        header = (
            ["j1", "j4", "j2", "j3"] +
            [f"Eigenvalue{i+1}" for i in range(num_eigenvalues)] +
            ["e3", "e4"] +
            [f"First Eigenvector Comp {i+1}" for i in range(num_eigenvalues)]
        )
        file.write(", ".join(header) + "\n")
        
        # Loop independently over j2 and j3
        for j2 in np.arange(*j2_range):
            for j3 in np.arange(*j3_range):
                # Compute numerical matrix
                numeric_hamiltonian = np.array(h_func(j2, j3)).astype(float)
                print(j1,j2,j3,j4)
                print (numeric_hamiltonian)
                # Solve eigenvalues and eigenvectors
                eigenvalues, eigenvectors = eigh(numeric_hamiltonian)
                
                # Compute e3 and e4
                e3 = -(constant_values[j1] + j2 + j3) / 4 
                e4 = -(constant_values[j1] + j2 + j3) / 4 
                
                # Prepare results for writing
                const_values_str = ", ".join([f"{constant_values[p]:.5f}" for p in constant_values])
                varying_values_str = f"{j2:.5f}, {j3:.5f}"
                eigenvalues_str = ", ".join([f"{ev:.5f}" for ev in eigenvalues])
                e_values_str = f"{e3:.5f}, {e4:.5f}"
                first_eigenvector_str = ", ".join([f"{comp:.5f}" for comp in eigenvectors[:, 0]])
                
                # Write to file
                file.write(f"{const_values_str}, {varying_values_str}, {eigenvalues_str}, {e_values_str}, {first_eigenvector_str}\n")



# Define symbolic variables
j1, j2, j3, j4 = symbols('j1 j2 j3 j4')

# Define a block Hamiltonian with symbolic variables
H_block = Matrix([
    [3*j1/4, np.sqrt(3)*(j2-j3)/4],
    [np.sqrt(3)*(j2-j3)/4, -j1/4 + j2/2 + j3/2]
])

# Parameter ranges
constant_values = {j1: 1.0, j4: 0.0}
j2_range = (-1.0, 1.0, 0.1)
j3_range = (-1.0, 1.0, 0.1)

# Solve and save results
solve_hamiltonian_fixed_j1_j4(H_block, [j1, j2, j3, j4], constant_values, j2_range, j3_range)

print("Results saved to 'hamiltonian_results_j2_j3.csv'")


j1 -1.0 -1.0 j4
[[ 0.75  0.  ]
 [ 0.   -1.25]]
j1 -1.0 -0.9 j4
[[ 0.75       -0.04330127]
 [-0.04330127 -1.2       ]]
j1 -1.0 -0.8 j4
[[ 0.75       -0.08660254]
 [-0.08660254 -1.15      ]]
j1 -1.0 -0.7000000000000001 j4
[[ 0.75       -0.12990381]
 [-0.12990381 -1.1       ]]
j1 -1.0 -0.6000000000000001 j4
[[ 0.75       -0.17320508]
 [-0.17320508 -1.05      ]]
j1 -1.0 -0.5000000000000001 j4
[[ 0.75       -0.21650635]
 [-0.21650635 -1.        ]]
j1 -1.0 -0.40000000000000013 j4
[[ 0.75       -0.25980762]
 [-0.25980762 -0.95      ]]
j1 -1.0 -0.30000000000000016 j4
[[ 0.75       -0.30310889]
 [-0.30310889 -0.9       ]]
j1 -1.0 -0.20000000000000018 j4
[[ 0.75       -0.34641016]
 [-0.34641016 -0.85      ]]
j1 -1.0 -0.1000000000000002 j4
[[ 0.75       -0.38971143]
 [-0.38971143 -0.8       ]]
j1 -1.0 -2.220446049250313e-16 j4
[[ 0.75      -0.4330127]
 [-0.4330127 -0.75     ]]
j1 -1.0 0.09999999999999964 j4
[[ 0.75       -0.47631397]
 [-0.47631397 -0.7       ]]
j1 -1.0 0.19999999999999973 j4
[[ 0

In [31]:
import numpy as np
from sympy import symbols, Matrix
from sympy.utilities.lambdify import lambdify
from scipy.linalg import eigh
# Define symbolic variables
j1, j2, j3, j4 = symbols('j1 j2 j3 j4')

# Define the block Hamiltonian with symbolic variables


# Set constant values and parameter ranges
constant_values = {j1: 1.0, j2: 0.0}
j3_range = (-1.0, 1.0, 0.1)  # Varying j3
j4_range = (-1.0, 1.0, 0.1)  # Varying j4
def solve_hamiltonian_fixed_j1_j2(hamiltonian, params, constant_values, j3_range, j4_range, filename="hamiltonian_results_j1_1_j3_j4.csv"):
    """
    Solves a symbolic Hamiltonian with j1 and j2 constant, looping over j3 and j4 independently.
    Saves eigenvalues as separate columns and only the first eigenvector.
    
    Parameters:
    - hamiltonian: SymPy matrix representing the Hamiltonian.
    - params: List of sympy symbols used as variables.
    - constant_values: Dictionary with fixed values for parameters.
    - j3_range: Tuple (start, stop, step) for j3.
    - j4_range: Tuple (start, stop, step) for j4.
    - filename: Output file name for results.
    """
    # Substitute constant values
    hamiltonian_substituted = hamiltonian.subs(constant_values)
    varying_params = [p for p in params if p not in constant_values]
    
    # Convert symbolic matrix to numerical function
    h_func = lambdify(varying_params, hamiltonian_substituted, modules="numpy")
    
# Prepare file for writing results
    with open(filename, 'w') as file:
        # Header setup
        num_eigenvalues = hamiltonian.shape[0]
        header = (
            ["j1", "j2", "j3", "j4"] +
            [f"Eigenvalue{i+1}" for i in range(num_eigenvalues)] +
            ["e3", "e4"] +
            [f"First Eigenvector Comp {i+1}" for i in range(num_eigenvalues)]
        )
        file.write(", ".join(header) + "\n")
        
        # Loop independently over j3 and j4
        for j3 in np.arange(*j3_range):
            for j4 in np.arange(*j4_range):
                # Compute numerical matrix
                numeric_hamiltonian = np.array(h_func(j3, j4)).astype(float)
                #print (numeric_hamiltonian)

                # Solve eigenvalues and eigenvectors
                eigenvalues, eigenvectors = eigh(numeric_hamiltonian)
                
                # Compute e3 and e4
                e3 = -(constant_values[j1] + constant_values[j2] + j3) / 4 + np.sqrt(3) * j4 / 2
                e4 = -(constant_values[j1] + constant_values[j2] + j3) / 4 - np.sqrt(3) * j4 / 2
                print(e3,e4)

                # Prepare results for writing
                const_values_str = ", ".join([f"{constant_values[p]:.5f}" for p in constant_values])
                varying_values_str = f"{j3:.5f}, {j4:.5f}"
                eigenvalues_str = ", ".join([f"{ev:.5f}" for ev in eigenvalues])
                e_values_str = f"{e3:.5f}, {e4:.5f}"
                first_eigenvector_str = ", ".join([f"{comp:.5f}" for comp in eigenvectors[:, 0]])
                
                # Write to file
                file.write(f"{const_values_str}, {varying_values_str}, {eigenvalues_str}, {e_values_str}, {first_eigenvector_str}\n")




# Solve and save results
solve_hamiltonian_fixed_j1_j2(H_block, [j1, j2, j3, j4], constant_values, j3_range, j4_range)

print("Results saved to 'hamiltonian_results_j3_j4.csv'")


-0.8660254037844386 0.8660254037844386
-0.7794228634059948 0.7794228634059948
-0.6928203230275509 0.6928203230275509
-0.6062177826491071 0.6062177826491071
-0.5196152422706632 0.5196152422706632
-0.4330127018922194 0.4330127018922194
-0.34641016151377557 0.34641016151377557
-0.25980762113533173 0.25980762113533173
-0.17320508075688787 0.17320508075688787
-0.08660254037844403 0.08660254037844403
-1.9229626863835638e-16 1.9229626863835638e-16
0.08660254037844355 -0.08660254037844355
0.17320508075688748 -0.17320508075688748
0.2598076211353314 -0.2598076211353314
0.3464101615137752 -0.3464101615137752
0.4330127018922189 -0.4330127018922189
0.5196152422706628 -0.5196152422706628
0.6062177826491068 -0.6062177826491068
0.6928203230275505 -0.6928203230275505
0.7794228634059943 -0.7794228634059943
-0.8910254037844386 0.8410254037844386
-0.8044228634059948 0.7544228634059947
-0.7178203230275509 0.6678203230275509
-0.6312177826491071 0.5812177826491071
-0.5446152422706633 0.4946152422706632
-0.45

In [32]:
import numpy as np
from sympy import symbols, Matrix
from sympy.utilities.lambdify import lambdify
from scipy.linalg import eigh
# Define symbolic variables
j1, j2, j3, j4 = symbols('j1 j2 j3 j4')

# Define the block Hamiltonian with symbolic variables


# Set constant values and parameter ranges
constant_values = {j1: 1.0, j3: 0.0}
j2_range = (-1.0, 1.0, 0.1)  # Varying j3
j4_range = (-1.0, 1.0, 0.1)  # Varying j4
def solve_hamiltonian_fixed_j1_j3(hamiltonian, params, constant_values, j2_range, j4_range, filename="hamiltonian_results_j1_1_j2_j4.csv"):
    """
    Solves a symbolic Hamiltonian with j1 and j2 constant, looping over j3 and j4 independently.
    Saves eigenvalues as separate columns and only the first eigenvector.
    
    Parameters:
    - hamiltonian: SymPy matrix representing the Hamiltonian.
    - params: List of sympy symbols used as variables.
    - constant_values: Dictionary with fixed values for parameters.
    - j3_range: Tuple (start, stop, step) for j3.
    - j4_range: Tuple (start, stop, step) for j4.
    - filename: Output file name for results.
    """
    # Substitute constant values
    hamiltonian_substituted = hamiltonian.subs(constant_values)
    varying_params = [p for p in params if p not in constant_values]
    
    # Convert symbolic matrix to numerical function
    h_func = lambdify(varying_params, hamiltonian_substituted, modules="numpy")
    
# Prepare file for writing results
    with open(filename, 'w') as file:
        # Header setup
        num_eigenvalues = hamiltonian.shape[0]
        header = (
            ["j1", "j3", "j2", "j4"] +
            [f"Eigenvalue{i+1}" for i in range(num_eigenvalues)] +
            ["e3", "e4"] +
            [f"First Eigenvector Comp {i+1}" for i in range(num_eigenvalues)]
        )
        file.write(", ".join(header) + "\n")
        
        # Loop independently over j2 and j4
        for j2 in np.arange(*j2_range):
            for j4 in np.arange(*j4_range):
                # Compute numerical matrix
                numeric_hamiltonian = np.array(h_func(j2, j4)).astype(float)
                #print(j1,j2,j3,j4)
                #print(numeric_hamiltonian)
                # Solve eigenvalues and eigenvectors
                eigenvalues, eigenvectors = eigh(numeric_hamiltonian)
                
                # Compute e3 and e4
                e3 = -(constant_values[j1] + constant_values[j3] + j2) / 4 + np.sqrt(3) * j4 / 2
                e4 = -(constant_values[j1] + constant_values[j3] + j2) / 4 - np.sqrt(3) * j4 / 2
                print(e3,e4)
                # Prepare results for writing
                const_values_str = ", ".join([f"{constant_values[p]:.5f}" for p in constant_values])
                varying_values_str = f"{j2:.5f}, {j4:.5f}"
                eigenvalues_str = ", ".join([f"{ev:.5f}" for ev in eigenvalues])
                e_values_str = f"{e3:.5f}, {e4:.5f}"
                first_eigenvector_str = ", ".join([f"{comp:.5f}" for comp in eigenvectors[:, 0]])
                
                # Write to file
                file.write(f"{const_values_str}, {varying_values_str}, {eigenvalues_str}, {e_values_str}, {first_eigenvector_str}\n")




# Solve and save results
solve_hamiltonian_fixed_j1_j3(H_block, [j1, j2, j3, j4], constant_values, j2_range, j4_range)

print("Results saved to 'hamiltonian_results_j2_j4.csv'")


-0.8660254037844386 0.8660254037844386
-0.7794228634059948 0.7794228634059948
-0.6928203230275509 0.6928203230275509
-0.6062177826491071 0.6062177826491071
-0.5196152422706632 0.5196152422706632
-0.4330127018922194 0.4330127018922194
-0.34641016151377557 0.34641016151377557
-0.25980762113533173 0.25980762113533173
-0.17320508075688787 0.17320508075688787
-0.08660254037844403 0.08660254037844403
-1.9229626863835638e-16 1.9229626863835638e-16
0.08660254037844355 -0.08660254037844355
0.17320508075688748 -0.17320508075688748
0.2598076211353314 -0.2598076211353314
0.3464101615137752 -0.3464101615137752
0.4330127018922189 -0.4330127018922189
0.5196152422706628 -0.5196152422706628
0.6062177826491068 -0.6062177826491068
0.6928203230275505 -0.6928203230275505
0.7794228634059943 -0.7794228634059943
-0.8910254037844386 0.8410254037844386
-0.8044228634059948 0.7544228634059947
-0.7178203230275509 0.6678203230275509
-0.6312177826491071 0.5812177826491071
-0.5446152422706633 0.4946152422706632
-0.45