In [108]:
import numpy as np
from sympy import symbols, Matrix
from sympy import Symbol

# === 1. Define Symbolic Basis States ===
# These are symbolic representations for formal mathematical expressions
ket_ppp = symbols(r'|+++\rangle')  
ket_ppm = symbols(r'|++-\rangle')  
ket_pmp = symbols(r'|+-+\rangle')  
ket_pmm = symbols(r'|+--\rangle')  
ket_mpp = symbols(r'|-++\rangle')  
ket_mpm = symbols(r'|-+-\rangle')  
ket_mmp = symbols(r'|--+\rangle')  
ket_mmm = symbols(r'|---\rangle')

# === 2. Computational Basis Representation ===
# We represent the 3-qubit states as 8-dimensional column vectors
ket_0 = np.array([[1], [0]])  # |0>
ket_1 = np.array([[0], [1]])  # |1>

# Tensor product to create 3-qubit basis states (8-dimensional vectors)
ket_mmm_vec = np.kron(np.kron(ket_1, ket_1), ket_1)  # |+++>
ket_mmp_vec = np.kron(np.kron(ket_1, ket_1), ket_0)  # |++->
ket_mpm_vec = np.kron(np.kron(ket_1, ket_0), ket_1)  # |+-+>
ket_mpp_vec = np.kron(np.kron(ket_1, ket_0), ket_0)  # |+-->
ket_pmm_vec = np.kron(np.kron(ket_0, ket_1), ket_1)  # |-++>
ket_pmp_vec = np.kron(np.kron(ket_0, ket_1), ket_0)  # |-+->
ket_ppm_vec = np.kron(np.kron(ket_0, ket_0), ket_1)  # |--+>
ket_ppp_vec = np.kron(np.kron(ket_0, ket_0), ket_0)  # |--->

# Store all vectors in a dictionary for easy access
basis_states = {
    ket_ppp: ket_ppp_vec,
    ket_ppm: ket_ppm_vec,
    ket_pmp: ket_pmp_vec,
    ket_pmm: ket_pmm_vec,
    ket_mpp: ket_mpp_vec,
    ket_mpm: ket_mpm_vec,
    ket_mmp: ket_mmp_vec,
    ket_mmm: ket_mmm_vec
}

# === 3. Define a Linear Combination of Basis States ===
#a, b, c, d = symbols('a b c d')  # Coefficients for a generic ket
alpha, beta, gamma, delta = symbols('alpha beta gamma delta')

xi_ppm = Symbol(r'|\xi_{++-}\rangle')

# Symbolic expression for a ket
xi_ppm = 1/np.sqrt(2)*(ket_ppm+ket_mpp) 

# Numeric representation
xi_ppm_vec = 1/np.sqrt(2)*(ket_ppm_vec+ket_mpp_vec) 
#print(xi_ppm_vec)

xi_1_plus = symbols(r'\xi_{1+}')

xi_1_plus = alpha*ket_pmp + beta*xi_ppm
xi_1_plus_vec = alpha*ket_pmp_vec + beta*xi_ppm_vec

print(xi_1_plus)

xi_mmp = Symbol(r'|\xi_{--+}\rangle')


# Symbolic expression for a ket
xi_mmp = 1/np.sqrt(2)*(ket_mmp+ket_pmm) 

# Numeric representation
xi_mmp_vec = 1/np.sqrt(2)*(ket_mmp_vec+ket_pmm_vec) 
#print(xi_ppm_vec)

xi_1_minus = symbols(r'\xi_{1-}')

xi_1_minus = alpha*ket_mpm + beta*xi_mmp
xi_1_minus_vec = alpha*ket_mpm_vec + beta*xi_mmp_vec

#print(xi_1_plus)
test = np.outer(ket_mmm_vec,ket_mmm_vec)
#print(ket_ppm_vec,test)

# === 4. Compute an Outer Product Matrix ===
# Example: Creating a symbolic density matrix
outer_product_matrix = np.outer(xi_1_plus_vec, xi_1_plus_vec) + np.outer(xi_1_minus_vec, xi_1_minus_vec)

# === 5. Print Results ===
#print("Symbolic Ket Representation:", ket_symbolic)
#print("\nNumeric Ket Representation:\n", ket_vector)
print("\nOuter Product Matrix:\n", outer_product_matrix)
#print(xi_1_minus)



alpha*|+-+\rangle + beta*(0.707106781186547*|++-\rangle + 0.707106781186547*|-++\rangle)

Outer Product Matrix:
 [[0 0 0 0 0 0 0 0]
 [0 0.5*beta**2 0.707106781186547*alpha*beta 0 0.5*beta**2 0 0 0]
 [0 0.707106781186547*alpha*beta alpha**2 0 0.707106781186547*alpha*beta
  0 0 0]
 [0 0 0 0.5*beta**2 0 0.707106781186547*alpha*beta 0.5*beta**2 0]
 [0 0.5*beta**2 0.707106781186547*alpha*beta 0 0.5*beta**2 0 0 0]
 [0 0 0 0.707106781186547*alpha*beta 0 alpha**2
  0.707106781186547*alpha*beta 0]
 [0 0 0 0.5*beta**2 0 0.707106781186547*alpha*beta 0.5*beta**2 0]
 [0 0 0 0 0 0 0 0]]


In [109]:
xi_ppm = Symbol(r'|\xi_{++-}\rangle')

# Symbolic expression for a ket
xi_ppm = 1/np.sqrt(2)*(ket_ppm+ket_mpp) 

# Numeric representation
xi_ppm_vec = 1/np.sqrt(2)*(ket_ppm_vec+ket_mpp_vec) 
#print(xi_ppm_vec)

xi_2_plus = symbols(r'\xi_{2+}')

xi_2_plus = beta*ket_pmp - alpha*xi_ppm
xi_2_plus_vec = beta*ket_pmp_vec - alpha*xi_ppm_vec

print(xi_1_plus)

xi_mmp = Symbol(r'|\xi_{--+}\rangle')


# Symbolic expression for a ket
xi_mmp = 1/np.sqrt(2)*(ket_mmp+ket_pmm) 

# Numeric representation
xi_mmp_vec = 1/np.sqrt(2)*(ket_mmp_vec+ket_pmm_vec) 
#print(xi_ppm_vec)

xi_2_minus = symbols(r'\xi_{2-}')

xi_2_minus = beta*ket_mpm - alpha*xi_mmp
xi_2_minus_vec = beta*ket_mpm_vec - alpha*xi_mmp_vec

#print(xi_1_plus)
test = np.outer(ket_mmm_vec,ket_mmm_vec)
#print(ket_ppm_vec,test)

# === 4. Compute an Outer Product Matrix ===
# Example: Creating a symbolic density matrix
outer_product_matrix = np.outer(xi_2_plus_vec, xi_2_plus_vec) + np.outer(xi_2_minus_vec, xi_2_minus_vec)


# === 5. Print Results ===
#print("Symbolic Ket Representation:", ket_symbolic)
#print("\nNumeric Ket Representation:\n", ket_vector)
print("\nOuter Product Matrix:\n", outer_product_matrix)
#print(xi_1_minus)


alpha*|+-+\rangle + beta*(0.707106781186547*|++-\rangle + 0.707106781186547*|-++\rangle)

Outer Product Matrix:
 [[0 0 0 0 0 0 0 0]
 [0 0.5*alpha**2 -0.707106781186547*alpha*beta 0 0.5*alpha**2 0 0 0]
 [0 -0.707106781186547*alpha*beta beta**2 0 -0.707106781186547*alpha*beta
  0 0 0]
 [0 0 0 0.5*alpha**2 0 -0.707106781186547*alpha*beta 0.5*alpha**2 0]
 [0 0.5*alpha**2 -0.707106781186547*alpha*beta 0 0.5*alpha**2 0 0 0]
 [0 0 0 -0.707106781186547*alpha*beta 0 beta**2
  -0.707106781186547*alpha*beta 0]
 [0 0 0 0.5*alpha**2 0 -0.707106781186547*alpha*beta 0.5*alpha**2 0]
 [0 0 0 0 0 0 0 0]]


In [110]:
outer_product_g1 = 2*np.outer(ket_ppp_vec, ket_ppp_vec) + 2*np.outer(ket_mmm_vec, ket_mmm_vec) + np.outer(ket_ppm_vec,ket_ppm_vec)+ np.outer(ket_pmm_vec,ket_pmm_vec)+np.outer(ket_mmp_vec,ket_mmp_vec) +np.outer(ket_mpp_vec,ket_mpp_vec)
print("\nOuter Product Matrix:\n", outer_product_g1)




Outer Product Matrix:
 [[2 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 2]]


In [111]:
#outer_product_g6_s1 = np.outer(ket_ppp_vec, ket_ppp_vec) + np.outer(ket_ppm_vec,ket_ppm_vec)+ np.outer(ket_ppm_vec,ket_pmp_vec)+np.outer(ket_pmp_vec,ket_ppm_vec) +np.outer(ket_pmp_vec,ket_pmp_vec) + np.outer(ket_pmm_vec,ket_pmm_vec)
#print("\nOuter Product Matrix:\n", outer_product_g6)



In [112]:
test = np.outer(ket_ppm_vec, ket_pmp_vec) + np.outer(ket_pmp_vec,ket_ppm_vec)
print("\nOuter Product Matrix:\n", test)



Outer Product Matrix:
 [[0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [113]:
outer_product_g6 = np.outer(ket_ppm_vec, ket_pmp_vec) + np.outer(ket_pmp_vec,ket_ppm_vec) + np.outer(ket_mpp_vec, ket_pmp_vec) + np.outer(ket_pmp_vec,ket_mpp_vec) - (np.outer(ket_pmm_vec, ket_mpm_vec) + np.outer(ket_mpm_vec,ket_pmm_vec) + np.outer(ket_mpm_vec, ket_mmp_vec) + np.outer(ket_mmp_vec,ket_mpm_vec))

print("\nOuter Product Matrix:\n", outer_product_g6)



Outer Product Matrix:
 [[ 0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0]
 [ 0  1  0  0  1  0  0  0]
 [ 0  0  0  0  0 -1  0  0]
 [ 0  0  1  0  0  0  0  0]
 [ 0  0  0 -1  0  0 -1  0]
 [ 0  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0  0]]


In [114]:
import numpy as np
import sympy as sp
from sympy.physics.quantum import TensorProduct
from sympy.physics.quantum.dagger import Dagger
from sympy.physics.quantum import InnerProduct, OuterProduct
from sympy.physics.quantum.state import Ket, Bra



def convert_to_z_basis(state):
    """Convert a single qubit state from X or Y basis to Z basis representation."""
    theta = sp.Symbol('theta', real=True)
    if state == '|+>_x':
        return (1/sp.sqrt(2)) * sp.Matrix([[sp.exp(-1j * theta / 2)], [sp.exp(1j * theta / 2)]])  # (|0> + |1>)/sqrt(2)
    elif state == '|->_x':
        return (1/sp.sqrt(2)) * sp.Matrix([[sp.exp(-1j * theta / 2)], [-sp.exp(1j * theta / 2)]])  # (|0> - |1>)/sqrt(2)
    elif state == '|+>_y':
        return (1/sp.sqrt(2)) * sp.Matrix([[sp.exp(-1j * theta / 2)], [1j*sp.exp(1j * theta / 2)]])  # (|0> + i|1>)/sqrt(2)
    elif state == '|->_y':
        return (1/sp.sqrt(2)) * sp.Matrix([[sp.exp(-1j * theta / 2)], [-1j*sp.exp(1j * theta / 2)]])  # (|0> - i|1>)/sqrt(2)
    elif state == '|+>_z':
        return sp.Matrix([[sp.exp(-1j * theta / 2)], [0]])  # e^(-iθ/2)|0>
    elif state == '|->_z':
        return sp.Matrix([[0], [sp.exp(1j * theta / 2)]])  # e^(iθ/2)|1>
    else:
        raise ValueError(f"Unknown state: {state}")

def tensor_product(*states):
    """Compute the tensor product of multiple states and return as a matrix."""
    result = states[0]
    for state in states[1:]:
        result = TensorProduct(result, state)  # Convert tensor result to a mutable matrix
    return result.reshape(len(result), 1)  # Ensure column matrix output

def outer_product(state_vector):
    """Compute the outer product |ψ⟩⟨ψ| using SymPy's built-in outer product method."""
    #print(Ket('state_vector'))
    #print(Bra('state_vector'))
    return sp.tensorproduct(state_vector,Dagger(state_vector))
    #return Dagger(OuterProduct(Ket('state_vector'), Bra('state_vector')))
 # Built-in outer product

def quantum_state_multiplier(state_list):
    """Given a list of quantum states in different bases, compute the outer product of the final state."""
    converted_states = [convert_to_z_basis(state) for state in state_list]
    full_state = tensor_product(*converted_states)
    
    #print(full_state)
    #print(Dagger(full_state))
      # Ensure full_state is a matrix
    density_matrix = outer_product(full_state)

    # Dynamically replace all exponent terms with 0
    density_matrix = density_matrix.replace(lambda expr: expr.has(sp.exp), lambda _: 0)
    
    # Save full matrix to file for better viewing
    with open("density_matrix.txt", "w", encoding="utf-8") as f:
        f.write(sp.pretty(density_matrix))
    
    return density_matrix

# Example Usage
state_list = ['|+>_y', '|+>_y', '|->_y']  # Input state example
result_matrix = quantum_state_multiplier(state_list)


# Display first few rows and columns if matrix is too large
#rows, cols = result_matrix.shape
#preview_size = min(5, rows), min(5, cols)
sp.pretty_print(result_matrix)  # Show a small preview

print("Full density matrix saved to 'density_matrix.txt'")

⎡      [[1/8  0  0  0  0  0  0  0]]      ⎤
⎢                                        ⎥
⎢[[0  0.125  -0.125  0  -0.125  0  0  0]]⎥
⎢                                        ⎥
⎢[[0  -0.125  0.125  0  0.125  0  0  0]] ⎥
⎢                                        ⎥
⎢[[0  0  0  0.125  0  0.125  -0.125  0]] ⎥
⎢                                        ⎥
⎢[[0  -0.125  0.125  0  0.125  0  0  0]] ⎥
⎢                                        ⎥
⎢[[0  0  0  0.125  0  0.125  -0.125  0]] ⎥
⎢                                        ⎥
⎢[[0  0  0  -0.125  0  -0.125  0.125  0]]⎥
⎢                                        ⎥
⎣     [[0  0  0  0  0  0  0  0.125]]     ⎦
Full density matrix saved to 'density_matrix.txt'


In [150]:
#state 30
state_list1 = ['|+>_x', '|+>_y', '|->_x']  # Input state example
state_list2 = ['|->_x', '|->_y', '|+>_x']  # Input state example
state_list3 = ['|->_x', '|+>_y', '|+>_x']  # Input state example
state_list4 = ['|+>_x', '|->_y', '|->_x']  # Input state example


result_matrix = 1/4*(quantum_state_multiplier(state_list1) +quantum_state_multiplier(state_list2) +quantum_state_multiplier(state_list3) +quantum_state_multiplier(state_list4))
sp.pretty_print(result_matrix)  # Show a small preview



⎡  [[0.125  0  0  0  0  0  0  0]]   ⎤
⎢                                   ⎥
⎢[[0  0.125  0  0  -0.125  0  0  0]]⎥
⎢                                   ⎥
⎢  [[0  0  0.125  0  0  0  0  0]]   ⎥
⎢                                   ⎥
⎢[[0  0  0  0.125  0  0  -0.125  0]]⎥
⎢                                   ⎥
⎢[[0  -0.125  0  0  0.125  0  0  0]]⎥
⎢                                   ⎥
⎢  [[0  0  0  0  0  0.125  0  0]]   ⎥
⎢                                   ⎥
⎢[[0  0  0  -0.125  0  0  0.125  0]]⎥
⎢                                   ⎥
⎣  [[0  0  0  0  0  0  0  0.125]]   ⎦


In [143]:
#state 6
state_list1 = ['|+>_z', '|+>_x', '|+>_x']  # Input state example
state_list2 = ['|+>_x', '|+>_x', '|+>_z']  # Input state example
state_list3 = ['|->_z', '|->_x', '|->_x']  # Input state example
state_list4 = ['|->_x', '|->_x', '|->_z']  # Input state example


result_matrix = 1/4*(quantum_state_multiplier(state_list1) +quantum_state_multiplier(state_list2) +quantum_state_multiplier(state_list3) +quantum_state_multiplier(state_list4))
sp.pretty_print(result_matrix)  # Show a small preview



⎡     [[0.125  0  0  0  0  0  0  0]]     ⎤
⎢                                        ⎥
⎢  [[0  0.125  0.0625  0  0  0  0  0]]   ⎥
⎢                                        ⎥
⎢[[0  0.0625  0.125  0  0.0625  0  0  0]]⎥
⎢                                        ⎥
⎢  [[0  0  0  0.125  0  0.0625  0  0]]   ⎥
⎢                                        ⎥
⎢  [[0  0  0.0625  0  0.125  0  0  0]]   ⎥
⎢                                        ⎥
⎢[[0  0  0  0.0625  0  0.125  0.0625  0]]⎥
⎢                                        ⎥
⎢  [[0  0  0  0  0  0.0625  0.125  0]]   ⎥
⎢                                        ⎥
⎣     [[0  0  0  0  0  0  0  0.125]]     ⎦


In [141]:
#state 13
state_list1 = ['|+>_z', '|->_z', '|+>_x']  # Input state example
state_list2 = ['|+>_x', '|->_z', '|+>_z']  # Input state example
state_list3 = ['|->_z', '|+>_z', '|->_x']  # Input state example
state_list4 = ['|->_x', '|+>_z', '|->_z']  # Input state example


result_matrix = quantum_state_multiplier(state_list1) +quantum_state_multiplier(state_list2) +quantum_state_multiplier(state_list3) +quantum_state_multiplier(state_list4)
sp.pretty_print(result_matrix)  # Show a small preview



⎡ [[0  0  0  0  0  0  0  0]] ⎤
⎢                            ⎥
⎢[[0  1/2  0  0  0  0  0  0]]⎥
⎢                            ⎥
⎢ [[0  0  1  0  0  0  0  0]] ⎥
⎢                            ⎥
⎢[[0  0  0  1/2  0  0  0  0]]⎥
⎢                            ⎥
⎢[[0  0  0  0  1/2  0  0  0]]⎥
⎢                            ⎥
⎢ [[0  0  0  0  0  1  0  0]] ⎥
⎢                            ⎥
⎢[[0  0  0  0  0  0  1/2  0]]⎥
⎢                            ⎥
⎣ [[0  0  0  0  0  0  0  0]] ⎦


In [ ]:
#state 7
state_list1 = ['|+>_z', '|+>_x', '|->_x']  # Input state example
state_list2 = ['|+>_x', '|->_x', '|->_z']  # Input state example
state_list3 = ['|->_z', '|->_x', '|+>_x']  # Input state example
state_list4 = ['|->_x', '|+>_x', '|+>_z']  # Input state example


result_matrix = quantum_state_multiplier(state_list1) +quantum_state_multiplier(state_list2) +quantum_state_multiplier(state_list3) +quantum_state_multiplier(state_list4)
sp.pretty_print(result_matrix)  # Show a small preview

⎡   [[1/2  0  0  0  0  0  0  0]]   ⎤
⎢                                  ⎥
⎢ [[0  1/2  -1/4  0  0  0  0  0]]  ⎥
⎢                                  ⎥
⎢[[0  -1/4  1/2  0  -1/4  0  0  0]]⎥
⎢                                  ⎥
⎢ [[0  0  0  1/2  0  -1/4  0  0]]  ⎥
⎢                                  ⎥
⎢ [[0  0  -1/4  0  1/2  0  0  0]]  ⎥
⎢                                  ⎥
⎢[[0  0  0  -1/4  0  1/2  -1/4  0]]⎥
⎢                                  ⎥
⎢ [[0  0  0  0  0  -1/4  1/2  0]]  ⎥
⎢                                  ⎥
⎣   [[0  0  0  0  0  0  0  1/2]]   ⎦


In [144]:
#state 8
state_list1 = ['|+>_z', '|->_x', '|->_x']  # Input state example
state_list2 = ['|+>_x', '|+>_x', '|->_z']  # Input state example
state_list3 = ['|->_z', '|+>_x', '|+>_x']  # Input state example
state_list4 = ['|->_x', '|->_x', '|+>_z']  # Input state example


result_matrix = 1/4*(quantum_state_multiplier(state_list1) +quantum_state_multiplier(state_list2) +quantum_state_multiplier(state_list3) +quantum_state_multiplier(state_list4))
sp.pretty_print(result_matrix)  # Show a small preview

⎡     [[0.125  0  0  0  0  0  0  0]]     ⎤
⎢                                        ⎥
⎢  [[0  0.125  0.0625  0  0  0  0  0]]   ⎥
⎢                                        ⎥
⎢[[0  0.0625  0.125  0  0.0625  0  0  0]]⎥
⎢                                        ⎥
⎢  [[0  0  0  0.125  0  0.0625  0  0]]   ⎥
⎢                                        ⎥
⎢  [[0  0  0.0625  0  0.125  0  0  0]]   ⎥
⎢                                        ⎥
⎢[[0  0  0  0.0625  0  0.125  0.0625  0]]⎥
⎢                                        ⎥
⎢  [[0  0  0  0  0  0.0625  0.125  0]]   ⎥
⎢                                        ⎥
⎣     [[0  0  0  0  0  0  0  0.125]]     ⎦


In [145]:
#state 9
state_list1 = ['|+>_x', '|+>_z', '|->_x']  # Input state example
state_list2 = ['|+>_x', '|->_z', '|->_x']  # Input state example
state_list3 = ['|->_x', '|+>_z', '|+>_x']  # Input state example
state_list4 = ['|->_x', '|->_z', '|+>_x']  # Input state example


result_matrix = 1/4*(quantum_state_multiplier(state_list1) +quantum_state_multiplier(state_list2) +quantum_state_multiplier(state_list3) +quantum_state_multiplier(state_list4))
sp.pretty_print(result_matrix)  # Show a small preview

⎡  [[0.125  0  0  0  0  0  0  0]]   ⎤
⎢                                   ⎥
⎢[[0  0.125  0  0  -0.125  0  0  0]]⎥
⎢                                   ⎥
⎢  [[0  0  0.125  0  0  0  0  0]]   ⎥
⎢                                   ⎥
⎢[[0  0  0  0.125  0  0  -0.125  0]]⎥
⎢                                   ⎥
⎢[[0  -0.125  0  0  0.125  0  0  0]]⎥
⎢                                   ⎥
⎢  [[0  0  0  0  0  0.125  0  0]]   ⎥
⎢                                   ⎥
⎢[[0  0  0  -0.125  0  0  0.125  0]]⎥
⎢                                   ⎥
⎣  [[0  0  0  0  0  0  0  0.125]]   ⎦


In [146]:
#state 10
state_list1 = ['|+>_x', '|+>_z', '|+>_x']  # Input state example
state_list2 = ['|->_x', '|->_z', '|->_x']  # Input state example



result_matrix = 1/2*(quantum_state_multiplier(state_list1) +quantum_state_multiplier(state_list2))
sp.pretty_print(result_matrix)  # Show a small preview



⎡  [[0.125  0  0  0  0  0  0  0]]  ⎤
⎢                                  ⎥
⎢[[0  0.125  0  0  0.125  0  0  0]]⎥
⎢                                  ⎥
⎢  [[0  0  0.125  0  0  0  0  0]]  ⎥
⎢                                  ⎥
⎢[[0  0  0  0.125  0  0  0.125  0]]⎥
⎢                                  ⎥
⎢[[0  0.125  0  0  0.125  0  0  0]]⎥
⎢                                  ⎥
⎢  [[0  0  0  0  0  0.125  0  0]]  ⎥
⎢                                  ⎥
⎢[[0  0  0  0.125  0  0  0.125  0]]⎥
⎢                                  ⎥
⎣  [[0  0  0  0  0  0  0  0.125]]  ⎦


In [140]:
#state 11
state_list1 = ['|+>_z', '|->_x', '|+>_x']  # Input state example
state_list2 = ['|+>_x', '|->_x', '|+>_z']  # Input state example
state_list3 = ['|->_z', '|+>_x', '|->_x']  # Input state example
state_list4 = ['|->_x', '|+>_x', '|->_z']  # Input state example


result_matrix = quantum_state_multiplier(state_list1) +quantum_state_multiplier(state_list2) +quantum_state_multiplier(state_list3) +quantum_state_multiplier(state_list4)
sp.pretty_print(result_matrix)  # Show a small preview

⎡   [[1/2  0  0  0  0  0  0  0]]   ⎤
⎢                                  ⎥
⎢ [[0  1/2  -1/4  0  0  0  0  0]]  ⎥
⎢                                  ⎥
⎢[[0  -1/4  1/2  0  -1/4  0  0  0]]⎥
⎢                                  ⎥
⎢ [[0  0  0  1/2  0  -1/4  0  0]]  ⎥
⎢                                  ⎥
⎢ [[0  0  -1/4  0  1/2  0  0  0]]  ⎥
⎢                                  ⎥
⎢[[0  0  0  -1/4  0  1/2  -1/4  0]]⎥
⎢                                  ⎥
⎢ [[0  0  0  0  0  -1/4  1/2  0]]  ⎥
⎢                                  ⎥
⎣   [[0  0  0  0  0  0  0  1/2]]   ⎦


In [134]:
#state 14
state_list1 = ['|+>_z', '|->_x', '|+>_z']  # Input state example
state_list2 = ['|->_z', '|+>_x', '|->_z']  # Input state example



result_matrix = quantum_state_multiplier(state_list1) +quantum_state_multiplier(state_list2) 
sp.pretty_print(result_matrix)  # Show a small preview



⎡[[1/2  0  0  0  0  0  0  0]]⎤
⎢                            ⎥
⎢ [[0  0  0  0  0  0  0  0]] ⎥
⎢                            ⎥
⎢[[0  0  1/2  0  0  0  0  0]]⎥
⎢                            ⎥
⎢ [[0  0  0  0  0  0  0  0]] ⎥
⎢                            ⎥
⎢ [[0  0  0  0  0  0  0  0]] ⎥
⎢                            ⎥
⎢[[0  0  0  0  0  1/2  0  0]]⎥
⎢                            ⎥
⎢ [[0  0  0  0  0  0  0  0]] ⎥
⎢                            ⎥
⎣[[0  0  0  0  0  0  0  1/2]]⎦


In [116]:
#state 15
state_list1 = ['|+>_x', '|+>_y', '|+>_z']  # Input state example
state_list2 = ['|->_z', '|+>_y', '|->_x']  # Input state example
state_list3 = ['|->_x', '|->_y', '|->_z']  # Input state example
state_list4 = ['|+>_z', '|->_y', '|+>_x']  # Input state example
state_list5 = ['|+>_z', '|+>_y', '|+>_x']  # Input state example
state_list6 = ['|->_x', '|+>_y', '|->_z']  # Input state example
state_list7 = ['|->_z', '|->_y', '|->_x']  # Input state example
state_list8 = ['|+>_x', '|->_y', '|+>_z']  # Input state example



result_matrix = quantum_state_multiplier(state_list1) +quantum_state_multiplier(state_list2) +quantum_state_multiplier(state_list3) +quantum_state_multiplier(state_list4)+quantum_state_multiplier(state_list5) +quantum_state_multiplier(state_list6) +quantum_state_multiplier(state_list7) +quantum_state_multiplier(state_list8)
sp.pretty_print(result_matrix)  # Show a small preview



⎡ [[1  0  0  0  0  0  0  0]] ⎤
⎢                            ⎥
⎢ [[0  1  0  0  0  0  0  0]] ⎥
⎢                            ⎥
⎢[[0  0  1.0  0  0  0  0  0]]⎥
⎢                            ⎥
⎢[[0  0  0  1.0  0  0  0  0]]⎥
⎢                            ⎥
⎢ [[0  0  0  0  1  0  0  0]] ⎥
⎢                            ⎥
⎢ [[0  0  0  0  0  1  0  0]] ⎥
⎢                            ⎥
⎢[[0  0  0  0  0  0  1.0  0]]⎥
⎢                            ⎥
⎣[[0  0  0  0  0  0  0  1.0]]⎦


In [117]:
#state 16
state_list1 = ['|+>_y', '|+>_z', '|+>_x']  # Input state example
state_list2 = ['|->_x', '|->_z', '|+>_y']  # Input state example
state_list3 = ['|->_y', '|->_z', '|->_x']  # Input state example
state_list4 = ['|+>_x', '|+>_z', '|->_y']  # Input state example
state_list5 = ['|+>_x', '|+>_z', '|+>_y']  # Input state example
state_list6 = ['|+>_y', '|->_z', '|->_x']  # Input state example
state_list7 = ['|->_x', '|->_z', '|->_y']  # Input state example
state_list8 = ['|->_y', '|+>_z', '|+>_x']  # Input state example



result_matrix = quantum_state_multiplier(state_list1) +quantum_state_multiplier(state_list2) +quantum_state_multiplier(state_list3) +quantum_state_multiplier(state_list4)+quantum_state_multiplier(state_list5) +quantum_state_multiplier(state_list6) +quantum_state_multiplier(state_list7) +quantum_state_multiplier(state_list8)
sp.pretty_print(result_matrix)  # Show a small preview



⎡ [[1  0  0  0  0  0  0  0]] ⎤
⎢                            ⎥
⎢[[0  1.0  0  0  0  0  0  0]]⎥
⎢                            ⎥
⎢ [[0  0  1  0  0  0  0  0]] ⎥
⎢                            ⎥
⎢[[0  0  0  1.0  0  0  0  0]]⎥
⎢                            ⎥
⎢[[0  0  0  0  1.0  0  0  0]]⎥
⎢                            ⎥
⎢[[0  0  0  0  0  1.0  0  0]]⎥
⎢                            ⎥
⎢[[0  0  0  0  0  0  1.0  0]]⎥
⎢                            ⎥
⎣[[0  0  0  0  0  0  0  1.0]]⎦


In [137]:
#state 26
state_list1 = ['|+>_x', '|+>_x', '|->_x']  # Input state example
state_list2 = ['|+>_x', '|->_x', '|->_x']  # Input state example
state_list3 = ['|->_x', '|+>_x', '|+>_x']  # Input state example
state_list4 = ['|->_x', '|->_x', '|+>_x']  # Input state example


result_matrix = quantum_state_multiplier(state_list1) +quantum_state_multiplier(state_list2) +quantum_state_multiplier(state_list3) +quantum_state_multiplier(state_list4)
sp.pretty_print(result_matrix)  # Show a small preview

⎡ [[1/2  0  0  0  0  0  0  0]]  ⎤
⎢                               ⎥
⎢[[0  1/2  0  0  -1/2  0  0  0]]⎥
⎢                               ⎥
⎢ [[0  0  1/2  0  0  0  0  0]]  ⎥
⎢                               ⎥
⎢[[0  0  0  1/2  0  0  -1/2  0]]⎥
⎢                               ⎥
⎢[[0  -1/2  0  0  1/2  0  0  0]]⎥
⎢                               ⎥
⎢ [[0  0  0  0  0  1/2  0  0]]  ⎥
⎢                               ⎥
⎢[[0  0  0  -1/2  0  0  1/2  0]]⎥
⎢                               ⎥
⎣ [[0  0  0  0  0  0  0  1/2]]  ⎦


In [148]:
#state 27
state_list1 = ['|+>_x', '|+>_x', '|+>_y']  # Input state example
state_list2 = ['|+>_y', '|->_x', '|->_x']  # Input state example
state_list3 = ['|->_x', '|->_x', '|->_y']  # Input state example
state_list4 = ['|->_y', '|+>_x', '|+>_x']  # Input state example
state_list5 = ['|+>_y', '|+>_x', '|+>_x']  # Input state example
state_list6 = ['|->_x', '|->_x', '|+>_y']  # Input state example
state_list7 = ['|->_y', '|->_x', '|->_x']  # Input state example
state_list8 = ['|+>_x', '|+>_x', '|->_y']  # Input state example



result_matrix = 1/8*(quantum_state_multiplier(state_list1) +quantum_state_multiplier(state_list2) +quantum_state_multiplier(state_list3) +quantum_state_multiplier(state_list4)+quantum_state_multiplier(state_list5) +quantum_state_multiplier(state_list6) +quantum_state_multiplier(state_list7) +quantum_state_multiplier(state_list8))
sp.pretty_print(result_matrix)  # Show a small preview



⎡     [[0.125  0  0  0  0  0  0  0]]     ⎤
⎢                                        ⎥
⎢  [[0  0.125  0.0625  0  0  0  0  0]]   ⎥
⎢                                        ⎥
⎢[[0  0.0625  0.125  0  0.0625  0  0  0]]⎥
⎢                                        ⎥
⎢  [[0  0  0  0.125  0  0.0625  0  0]]   ⎥
⎢                                        ⎥
⎢  [[0  0  0.0625  0  0.125  0  0  0]]   ⎥
⎢                                        ⎥
⎢[[0  0  0  0.0625  0  0.125  0.0625  0]]⎥
⎢                                        ⎥
⎢  [[0  0  0  0  0  0.0625  0.125  0]]   ⎥
⎢                                        ⎥
⎣     [[0  0  0  0  0  0  0  0.125]]     ⎦


In [147]:
#state 24
state_list1 = ['|+>_x', '|+>_x', '|+>_x']  # Input state example
state_list2 = ['|->_x', '|->_x', '|->_x']  # Input state example



result_matrix = 1/2*(quantum_state_multiplier(state_list1) +quantum_state_multiplier(state_list2) )
sp.pretty_print(result_matrix)  # Show a small preview



⎡    [[0.125  0  0  0  0  0  0  0]]    ⎤
⎢                                      ⎥
⎢[[0  0.125  0.125  0  0.125  0  0  0]]⎥
⎢                                      ⎥
⎢[[0  0.125  0.125  0  0.125  0  0  0]]⎥
⎢                                      ⎥
⎢[[0  0  0  0.125  0  0.125  0.125  0]]⎥
⎢                                      ⎥
⎢[[0  0.125  0.125  0  0.125  0  0  0]]⎥
⎢                                      ⎥
⎢[[0  0  0  0.125  0  0.125  0.125  0]]⎥
⎢                                      ⎥
⎢[[0  0  0  0.125  0  0.125  0.125  0]]⎥
⎢                                      ⎥
⎣    [[0  0  0  0  0  0  0  0.125]]    ⎦


In [121]:
#state 25
state_list1 = ['|+>_x', '|->_x', '|+>_x']  # Input state example
state_list2 = ['|->_x', '|+>_x', '|->_x']  # Input state example



result_matrix = quantum_state_multiplier(state_list1) +quantum_state_multiplier(state_list2) 
sp.pretty_print(result_matrix)  # Show a small preview



⎡   [[1/4  0  0  0  0  0  0  0]]   ⎤
⎢                                  ⎥
⎢[[0  1/4  -1/4  0  1/4  0  0  0]] ⎥
⎢                                  ⎥
⎢[[0  -1/4  1/4  0  -1/4  0  0  0]]⎥
⎢                                  ⎥
⎢[[0  0  0  1/4  0  -1/4  1/4  0]] ⎥
⎢                                  ⎥
⎢[[0  1/4  -1/4  0  1/4  0  0  0]] ⎥
⎢                                  ⎥
⎢[[0  0  0  -1/4  0  1/4  -1/4  0]]⎥
⎢                                  ⎥
⎢[[0  0  0  1/4  0  -1/4  1/4  0]] ⎥
⎢                                  ⎥
⎣   [[0  0  0  0  0  0  0  1/4]]   ⎦


In [139]:
#state 28
state_list1 = ['|+>_x', '|+>_y', '|+>_x']  # Input state example
state_list2 = ['|->_x', '|+>_y', '|->_x']  # Input state example
state_list3 = ['|->_x', '|->_y', '|->_x']  # Input state example
state_list4 = ['|+>_x', '|->_y', '|+>_x']  # Input state example


result_matrix = quantum_state_multiplier(state_list1) +quantum_state_multiplier(state_list2) +quantum_state_multiplier(state_list3) +quantum_state_multiplier(state_list4)
sp.pretty_print(result_matrix)  # Show a small preview



⎡ [[1/2  0  0  0  0  0  0  0]] ⎤
⎢                              ⎥
⎢[[0  1/2  0  0  1/2  0  0  0]]⎥
⎢                              ⎥
⎢ [[0  0  0.5  0  0  0  0  0]] ⎥
⎢                              ⎥
⎢[[0  0  0  0.5  0  0  0.5  0]]⎥
⎢                              ⎥
⎢[[0  1/2  0  0  1/2  0  0  0]]⎥
⎢                              ⎥
⎢ [[0  0  0  0  0  1/2  0  0]] ⎥
⎢                              ⎥
⎢[[0  0  0  0.5  0  0  0.5  0]]⎥
⎢                              ⎥
⎣ [[0  0  0  0  0  0  0  0.5]] ⎦


In [136]:
#state 29
state_list1 = ['|+>_x', '|->_x', '|+>_y']  # Input state example
state_list2 = ['|->_y', '|->_x', '|+>_x']  # Input state example
state_list3 = ['|->_x', '|+>_x', '|->_y']  # Input state example
state_list4 = ['|->_x', '|+>_x', '|+>_y']  # Input state example
state_list5 = ['|+>_y', '|->_x', '|+>_x']  # Input state example
state_list6 = ['|+>_x', '|->_x', '|->_y']  # Input state example
state_list7 = ['|->_y', '|+>_x', '|->_x']  # Input state example
state_list8 = ['|+>_y', '|+>_x', '|->_x']  # Input state example



result_matrix = quantum_state_multiplier(state_list1) +quantum_state_multiplier(state_list2) +quantum_state_multiplier(state_list3) +quantum_state_multiplier(state_list4)+quantum_state_multiplier(state_list5) +quantum_state_multiplier(state_list6) +quantum_state_multiplier(state_list7) +quantum_state_multiplier(state_list8)
sp.pretty_print(result_matrix)  # Show a small preview



⎡    [[1  0  0  0  0  0  0  0]]    ⎤
⎢                                  ⎥
⎢ [[0  1.0  -1/2  0  0  0  0  0]]  ⎥
⎢                                  ⎥
⎢ [[0  -1/2  1  0  -1/2  0  0  0]] ⎥
⎢                                  ⎥
⎢ [[0  0  0  1.0  0  -0.5  0  0]]  ⎥
⎢                                  ⎥
⎢ [[0  0  -1/2  0  1.0  0  0  0]]  ⎥
⎢                                  ⎥
⎢[[0  0  0  -0.5  0  1.0  -0.5  0]]⎥
⎢                                  ⎥
⎢ [[0  0  0  0  0  -0.5  1.0  0]]  ⎥
⎢                                  ⎥
⎣   [[0  0  0  0  0  0  0  1.0]]   ⎦
