In [8]:
import numpy as np
import scipy

In [29]:
# Use python3


j1 = 1.0
j4 = 0
j3 = -0
j2 = -0

e3 = -(j1+j2+j3)/4 + np.sqrt(3)*j4/2
e4 = -(j1+j2+j3)/4 - np.sqrt(3)*j4/2
ematrix = np.array([[3*j1/4, np.sqrt(3)*(j2-j3)/4],[np.sqrt(3)*(j2-j3)/4, -j1/4+j2/2 + j3/2]])
evals = np.linalg.eig(ematrix)
energy = np.array([evals[0][0], evals[0][1],e3,e4])
alpha = evals[1][0][0]
beta = evals[1][0][1]
c1 = np.sqrt(2/3)*np.abs(beta)*np.sqrt(1 - (beta**2)/3)
c2 = np.sqrt(2/3)*np.abs(alpha)*np.sqrt(1-(alpha**2)/3)
concurs = np.array([c1,c2,2/3,2/3,0])
print (evals,alpha,beta)

#quit()




#sample output for T = .2 is 
#density_fin
#array([-2.46020284e-09,  7.42972817e-02,  5.09902820e-01,  1.68645764e-01,
#        1.77262352e-10,  2.37289345e-01,  3.09826333e-10,  9.86478728e-03,
#        4.78084599e-10,  1.02943886e-09,  1.13515563e-09,  9.80079093e-10])
#concur_fin 0.501865264037816


EigResult(eigenvalues=array([ 0.75, -0.25]), eigenvectors=array([[1., 0.],
       [0., 1.]])) 1.0 0.0


In [30]:

def concurance(unent_arry,vecs):
    det = np.linalg.det(vecs)
    #print("det=", det)
    invstrans=np.linalg.pinv(np.transpose(vecs))


    unent_arry_inv = np.zeros((7,5), dtype = float)
    c_array = np.zeros((7), dtype = float)
    for count in range(0,7):
        unent_arry_inv[count] = np.matmul(invstrans,unent_arry[count])
        c_array[count] = (-1)*(np.dot(unent_arry_inv[count], concurs))
    #print(invstrans)
    #print(unent_arry_inv)
    #print(c_array)

    temp = .01 
    partit = np.sum(np.exp(-energy/temp))
    probs = np.exp(-energy/temp)/partit
    probs1 = np.pad(probs, (0,1))
    concur_init = np.dot(probs1,concurs)

    Au1 = np.transpose(unent_arry_inv)
    Au2 = (-1)*np.identity(7)
    Aub = np.append(Au1, Au2, axis=0)
    bub = np.pad(probs, (0,8))
    output = scipy.optimize.linprog(c_array, Aub, bub)
    concur_fin = concur_init+output.fun
    density_fin1 = probs1 
    for count in range(0,5):
        density_fin1[count] -= np.dot(output.x, Au1[count])
    density_fin2 = output.x
    density_fin = np.append(density_fin1, density_fin2)
    #print(partit)
    print(concur_init,probs,probs1)
    #print(concur_fin, density_fin)
    print(output)

In [31]:
unent_arry_1 = np.array([[0,0,0,0,1],[1/4,1/8,1/8,0,3/4],[1/4,-1/8,1/8,0,3/4],[1/4,1/24,-1/24,0,3/4], [1/4,-1/24,-1/24,0,3/4],[1/4,0,0,1/24,3/4],[1/4,0,0,-1/24,3/4]])
#vecs_1 = np.array([[.9974,.0146,.0004,0,.0026],[.0026 ,-.0146,.1662,0,.9974], [0,0,-.0833, .1443,1], [0,0,-.0833, -.1443,1], [1,0,0,0,0]])
vecs_1 = np.array([[alpha**2,alpha*beta/(2*np.sqrt(3)),beta**2/6,0,beta**2],[beta**2 ,-alpha*beta/(2*np.sqrt(3)),alpha**2/6,0,alpha**2], [0,0,-.0833, .1443,1], [0,0,-.0833, -.1443,1], [1,0,0,0,0]], dtype=np.float64)
print(alpha, beta, vecs_1)
unent_arry_2 = np.array([[1,0,0,0,0],[1/4,1/8,1/8,0,3/4],[1/4,-1/8,1/8,0,3/4],[1/4,1/24,-1/24,0,3/4], [1/4,-1/24,-1/24,0,3/4],[1/4,0,0,1/24,3/4],[1/4,0,0,-1/24,3/4]])
vecs_2 = np.array([[.9974,.0146,.0004,0,.0026],[.0026 ,-.0146,.1662,0,.9974], [0,0,-.0833, .1443,1], [0,0,-.0833, -.1443,1], [0,0,0,0,1]])
print(vecs_2)
unent_arry_3 = np.array([[0,0,0,0,1],[1,0,0,0,0],[1/4,-1/8,1/8,0,3/4],[1/4,1/24,-1/24,0,3/4], [1/4,-1/24,-1/24,0,3/4],[1/4,0,0,1/24,3/4],[1/4,0,0,-1/24,3/4]])
vecs_3 = np.array([[.9974,.0146,.0004,0,.0026],[.0026 ,-.0146,.1662,0,.9974], [0,0,-.0833, .1443,1], [0,0,-.0833, -.1443,1], [1/4,1/8,1/8,0,3/4]])

unent_arry_4 = np.array([[0,0,0,0,1],[1/4,1/8,1/8,0,3/4],[1,0,0,0,0],[1/4,1/24,-1/24,0,3/4], [1/4,-1/24,-1/24,0,3/4],[1/4,0,0,1/24,3/4],[1/4,0,0,-1/24,3/4]])
vecs_4 = np.array([[.9974,.0146,.0004,0,.0026],[.0026 ,-.0146,.1662,0,.9974], [0,0,-.0833, .1443,1], [0,0,-.0833, -.1443,1], [1/4,-1/8,1/8,0,3/4]])

unent_arry_5 = np.array([[0,0,0,0,1],[1/4,1/8,1/8,0,3/4],[1/4,-1/8,1/8,0,3/4],[1,0,0,0,0], [1/4,-1/24,-1/24,0,3/4],[1/4,0,0,1/24,3/4],[1/4,0,0,-1/24,3/4]])
vecs_5 = np.array([[.9974,.0146,.0004,0,.0026],[.0026 ,-.0146,.1662,0,.9974], [0,0,-.0833, .1443,1], [0,0,-.0833, -.1443,1], [1/4,1/24,-1/24,0,3/4]])

unent_arry_6 = np.array([[0,0,0,0,1],[1/4,1/8,1/8,0,3/4],[1/4,-1/8,1/8,0,3/4],[1/4,1/24,-1/24,0,3/4], [1,0,0,0,0],[1/4,0,0,1/24,3/4],[1/4,0,0,-1/24,3/4]])
vecs_6 = np.array([[.9974,.0146,.0004,0,.0026],[.0026 ,-.0146,.1662,0,.9974], [0,0,-.0833, .1443,1], [0,0,-.0833, -.1443,1], [1/4,-1/24,-1/24,0,3/4]])

unent_arry_7 = np.array([[0,0,0,0,1],[1/4,1/8,1/8,0,3/4],[1/4,-1/8,1/8,0,3/4],[1/4,1/24,-1/24,0,3/4], [1/4,-1/24,-1/24,0,3/4],[1,0,0,0,0],[1/4,0,0,-1/24,3/4]])
vecs_7 = np.array([[.9974,.0146,.0004,0,.0026],[.0026 ,-.0146,.1662,0,.9974], [0,0,-.0833, .1443,1], [0,0,-.0833, -.1443,1], [1/4,0,0,1/24,3/4]])

unent_arry_8 = np.array([[0,0,0,0,1],[1/4,1/8,1/8,0,3/4],[1/4,-1/8,1/8,0,3/4],[1/4,1/24,-1/24,0,3/4], [1/4,-1/24,-1/24,0,3/4],[1/4,0,0,1/24,3/4],[1,0,0,0,0]])
vecs_8 = np.array([[.9974,.0146,.0004,0,.0026],[.0026 ,-.0146,.1662,0,.9974], [0,0,-.0833, .1443,1], [0,0,-.0833, -.1443,1], [1/4,0,0,-1/24,3/4]])


1.0 0.0 [[ 1.          0.          0.          0.          0.        ]
 [ 0.         -0.          0.16666667  0.          1.        ]
 [ 0.          0.         -0.0833      0.1443      1.        ]
 [ 0.          0.         -0.0833     -0.1443      1.        ]
 [ 1.          0.          0.          0.          0.        ]]
[[ 9.974e-01  1.460e-02  4.000e-04  0.000e+00  2.600e-03]
 [ 2.600e-03 -1.460e-02  1.662e-01  0.000e+00  9.974e-01]
 [ 0.000e+00  0.000e+00 -8.330e-02  1.443e-01  1.000e+00]
 [ 0.000e+00  0.000e+00 -8.330e-02 -1.443e-01  1.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  1.000e+00]]


In [32]:
concurance(unent_arry_1,vecs_1)




0.6666666666666666 [1.24002533e-44 3.33333333e-01 3.33333333e-01 3.33333333e-01] [1.24002533e-44 1.33333333e-04 1.11022302e-16 0.00000000e+00
 0.00000000e+00]
        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -0.6665777777777784
              x: [ 9.999e-01 -0.000e+00  0.000e+00  0.000e+00  0.000e+00
                   0.000e+00  0.000e+00]
            nit: 0
          lower:  residual: [ 9.999e-01 -0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  6.667e-01
                              6.667e-01  2.113e-01  7.887e-01]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00]
     

In [34]:
concurance(unent_arry_2,vecs_2)



0.6666666666666666 [1.24002533e-44 3.33333333e-01 3.33333333e-01 3.33333333e-01] [1.24002533e-44 3.33333333e-01 3.33333333e-01 3.33333333e-01
 0.00000000e+00]
       message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
       success: True
        status: 0
           fun: 0.0
             x: [ 0.000e+00  0.000e+00 -0.000e+00  0.000e+00  0.000e+00
                  0.000e+00  0.000e+00]
           nit: 0
         lower:  residual: [ 0.000e+00  0.000e+00 -0.000e+00  0.000e+00
                             0.000e+00  0.000e+00  0.000e+00]
                marginals: [ 7.067e+01  3.734e+01  0.000e+00  2.356e+01
                             1.111e+01  1.767e+01  1.767e+01]
         upper:  residual: [       inf        inf        inf        inf
                                   inf        inf        inf]
                marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                             0.000e+00  0.000e+00  0.000e+00]
         eqlin:  residual: []
      

In [35]:
concurance(unent_arry_3,vecs_3)

0.6666666666666666 [1.24002533e-44 3.33333333e-01 3.33333333e-01 3.33333333e-01] [1.24002533e-44 3.33333333e-01 3.33333333e-01 3.33333333e-01
 0.00000000e+00]
       message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
       success: True
        status: 0
           fun: 0.0
             x: [-0.000e+00  0.000e+00 -0.000e+00  0.000e+00  0.000e+00
                  0.000e+00  0.000e+00]
           nit: 4
         lower:  residual: [-0.000e+00  0.000e+00 -0.000e+00  0.000e+00
                             0.000e+00  0.000e+00  0.000e+00]
                marginals: [ 0.000e+00  7.067e+01  0.000e+00  2.356e+01
                             1.111e+01  1.767e+01  1.767e+01]
         upper:  residual: [       inf        inf        inf        inf
                                   inf        inf        inf]
                marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                             0.000e+00  0.000e+00  0.000e+00]
         eqlin:  residual: []
      

In [106]:
concurance(unent_arry_4,vecs_4)

0.533510944147056 [0.         0.06003056 0.19311645 0.54715817 0.00797052 0.19172431
 0.         0.         0.         0.         0.         0.        ]


In [107]:
concurance(unent_arry_5,vecs_5)

0.5335109441470559 [ 6.50521303e-19  6.00305606e-02  1.93116447e-01  5.47158167e-01
 -4.59214216e-18  1.91724305e-01  0.00000000e+00  7.97051999e-03
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]


In [108]:
concurance(unent_arry_6,vecs_6)

0.533510944147056 [-4.33680869e-19  6.00305606e-02  1.93116447e-01  5.47158167e-01
  3.81723105e-19  1.91724305e-01  0.00000000e+00  7.97051999e-03
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]


In [109]:
#concurance(unent_arry_7,vecs_7)
#concurance(unent_arry_8,vecs_8)